/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CaseStudy = IDL.Record({
  'metrics' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
  'clientName' : IDL.Text,
  'description' : IDL.Text,
  'industry' : IDL.Text,
});
export const FAQItem = IDL.Record({
  'question' : IDL.Text,
  'answer' : IDL.Text,
});
export const PricingPlan = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'price' : IDL.Int,
});
export const Service = IDL.Record({
  'title' : IDL.Text,
  'icon' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const TeamMember = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'role' : IDL.Text,
  'quote' : IDL.Text,
  'author' : IDL.Text,
  'company' : IDL.Text,
  'rating' : IDL.Int,
});
export const ContactForm = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  'addCaseStudy' : IDL.Func([CaseStudy], [IDL.Int], []),
  'addFAQ' : IDL.Func([FAQItem], [IDL.Int], []),
  'addPricingPlan' : IDL.Func([PricingPlan], [IDL.Int], []),
  'addService' : IDL.Func([Service], [IDL.Int], []),
  'addTeamMember' : IDL.Func([TeamMember], [IDL.Int], []),
  'addTestimonial' : IDL.Func([Testimonial], [IDL.Int], []),
  'deleteCaseStudy' : IDL.Func([IDL.Int], [], []),
  'deleteFAQ' : IDL.Func([IDL.Int], [], []),
  'deletePricingPlan' : IDL.Func([IDL.Int], [], []),
  'deleteService' : IDL.Func([IDL.Int], [], []),
  'deleteTeamMember' : IDL.Func([IDL.Int], [], []),
  'deleteTestimonial' : IDL.Func([IDL.Int], [], []),
  'getCaseStudies' : IDL.Func([], [IDL.Vec(CaseStudy)], ['query']),
  'getFAQs' : IDL.Func([], [IDL.Vec(FAQItem)], ['query']),
  'getPricingPlans' : IDL.Func([], [IDL.Vec(PricingPlan)], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
  'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'submitContactForm' : IDL.Func([ContactForm], [IDL.Int], []),
  'updateCaseStudy' : IDL.Func([IDL.Int, CaseStudy], [], []),
  'updateFAQ' : IDL.Func([IDL.Int, FAQItem], [], []),
  'updatePricingPlan' : IDL.Func([IDL.Int, PricingPlan], [], []),
  'updateService' : IDL.Func([IDL.Int, Service], [], []),
  'updateTeamMember' : IDL.Func([IDL.Int, TeamMember], [], []),
  'updateTestimonial' : IDL.Func([IDL.Int, Testimonial], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CaseStudy = IDL.Record({
    'metrics' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text)),
    'clientName' : IDL.Text,
    'description' : IDL.Text,
    'industry' : IDL.Text,
  });
  const FAQItem = IDL.Record({ 'question' : IDL.Text, 'answer' : IDL.Text });
  const PricingPlan = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'price' : IDL.Int,
  });
  const Service = IDL.Record({
    'title' : IDL.Text,
    'icon' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const TeamMember = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'role' : IDL.Text,
    'quote' : IDL.Text,
    'author' : IDL.Text,
    'company' : IDL.Text,
    'rating' : IDL.Int,
  });
  const ContactForm = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    'addCaseStudy' : IDL.Func([CaseStudy], [IDL.Int], []),
    'addFAQ' : IDL.Func([FAQItem], [IDL.Int], []),
    'addPricingPlan' : IDL.Func([PricingPlan], [IDL.Int], []),
    'addService' : IDL.Func([Service], [IDL.Int], []),
    'addTeamMember' : IDL.Func([TeamMember], [IDL.Int], []),
    'addTestimonial' : IDL.Func([Testimonial], [IDL.Int], []),
    'deleteCaseStudy' : IDL.Func([IDL.Int], [], []),
    'deleteFAQ' : IDL.Func([IDL.Int], [], []),
    'deletePricingPlan' : IDL.Func([IDL.Int], [], []),
    'deleteService' : IDL.Func([IDL.Int], [], []),
    'deleteTeamMember' : IDL.Func([IDL.Int], [], []),
    'deleteTestimonial' : IDL.Func([IDL.Int], [], []),
    'getCaseStudies' : IDL.Func([], [IDL.Vec(CaseStudy)], ['query']),
    'getFAQs' : IDL.Func([], [IDL.Vec(FAQItem)], ['query']),
    'getPricingPlans' : IDL.Func([], [IDL.Vec(PricingPlan)], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getTeamMembers' : IDL.Func([], [IDL.Vec(TeamMember)], ['query']),
    'getTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'initialize' : IDL.Func([], [], []),
    'submitContactForm' : IDL.Func([ContactForm], [IDL.Int], []),
    'updateCaseStudy' : IDL.Func([IDL.Int, CaseStudy], [], []),
    'updateFAQ' : IDL.Func([IDL.Int, FAQItem], [], []),
    'updatePricingPlan' : IDL.Func([IDL.Int, PricingPlan], [], []),
    'updateService' : IDL.Func([IDL.Int, Service], [], []),
    'updateTeamMember' : IDL.Func([IDL.Int, TeamMember], [], []),
    'updateTestimonial' : IDL.Func([IDL.Int, Testimonial], [], []),
  });
};

export const init = ({ IDL }) => { return []; };