/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CaseStudy {
  'metrics' : Array<[string, string]>,
  'clientName' : string,
  'description' : string,
  'industry' : string,
}
export interface ContactForm {
  'name' : string,
  'email' : string,
  'company' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface FAQItem { 'question' : string, 'answer' : string }
export interface MembershipSubscription {
  'status' : string,
  'name' : string,
  'plan' : string,
  'tier' : string,
  'email' : string,
  'timestamp' : bigint,
  'phone' : string,
}
export interface PricingPlan {
  'features' : Array<string>,
  'name' : string,
  'isFeatured' : boolean,
  'price' : bigint,
}
export interface Service {
  'title' : string,
  'icon' : string,
  'description' : string,
  'category' : string,
}
export interface TeamMember { 'bio' : string, 'name' : string, 'role' : string }
export interface Testimonial {
  'role' : string,
  'quote' : string,
  'author' : string,
  'company' : string,
  'rating' : bigint,
}
export interface _SERVICE {
  'addCaseStudy' : ActorMethod<[CaseStudy], bigint>,
  'addFAQ' : ActorMethod<[FAQItem], bigint>,
  'addPricingPlan' : ActorMethod<[PricingPlan], bigint>,
  'addService' : ActorMethod<[Service], bigint>,
  'addTeamMember' : ActorMethod<[TeamMember], bigint>,
  'addTestimonial' : ActorMethod<[Testimonial], bigint>,
  'deleteCaseStudy' : ActorMethod<[bigint], undefined>,
  'deleteFAQ' : ActorMethod<[bigint], undefined>,
  'deletePricingPlan' : ActorMethod<[bigint], undefined>,
  'deleteService' : ActorMethod<[bigint], undefined>,
  'deleteTeamMember' : ActorMethod<[bigint], undefined>,
  'deleteTestimonial' : ActorMethod<[bigint], undefined>,
  'getCaseStudies' : ActorMethod<[], Array<CaseStudy>>,
  'getFAQs' : ActorMethod<[], Array<FAQItem>>,
  'getMembershipByEmail' : ActorMethod<[string], [] | [MembershipSubscription]>,
  'getMembershipSubscriptions' : ActorMethod<[], Array<MembershipSubscription>>,
  'getPricingPlans' : ActorMethod<[], Array<PricingPlan>>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getTeamMembers' : ActorMethod<[], Array<TeamMember>>,
  'getTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'initialize' : ActorMethod<[], undefined>,
  'submitContactForm' : ActorMethod<[ContactForm], bigint>,
  'subscribeMembership' : ActorMethod<[MembershipSubscription], bigint>,
  'updateCaseStudy' : ActorMethod<[bigint, CaseStudy], undefined>,
  'updateFAQ' : ActorMethod<[bigint, FAQItem], undefined>,
  'updatePricingPlan' : ActorMethod<[bigint, PricingPlan], undefined>,
  'updateService' : ActorMethod<[bigint, Service], undefined>,
  'updateTeamMember' : ActorMethod<[bigint, TeamMember], undefined>,
  'updateTestimonial' : ActorMethod<[bigint, Testimonial], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];